# Generated by Django 5.1.2 on 2024-11-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id_mascota', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('txtnombre', models.CharField(max_length=50)),
                ('txtespecie', models.CharField(max_length=50)),
                ('numedad', models.PositiveIntegerField()),
                ('numpeso', models.FloatField()),
                ('id_cliente', models.CharField(max_length=10)),
                ('txthistorial', models.CharField(max_length=50)),
            ],
        ),
    ]
