# Generated by Django 5.1.1 on 2024-12-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0002_rename_empleado_ventas_id_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='id_libro',
        ),
    ]
